config/routes.rb
Rails.application.routes.draw do
  mount Api => '/'

  devise_for :users

  resources :books do
    resources :chapters, :except => :index do
      resources :sections, :except => :show do
        resources :attachments, :except => [:index, :show]
      end
    end

    post 'sort' => 'books#sort', :as => :sort
  end

  root :to => 'books#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, :all if user.administrator?
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  mount_uploader :file, AttachmentUploader

  belongs_to :page

  validates_presence_of :file

  def content_type
    file.file.extension
  end

  def human_filename
    file.path.split("/").last
  end

  def is_image?
    %w(jpg jpeg png).include?(content_type)
  end

  def is_pdf?
    'pdf'.include?(content_type)
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user

  has_many :chapters, -> { order('position') }, :dependent => :destroy

  def sort_childrens(items)
    items.each_with_index do |id, index|
      Chapter.find(id).update_attributes(:position => index + 1)
    end
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :book

  has_many :sections, -> { order('position') }, :dependent => :destroy
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user

  extend Enumerize
  enumerize :role, :in => [:administrator], :predicates => true
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :chapter

  has_many :attachments, -> { order('position') }, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :permissions, :dependent => :destroy

  def administrator?
    permissions.where(:role => :administrator).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery :with => :exception

  before_filter :authenticate_user!

  layout 'public'

  rescue_from CanCan::AccessDenied do |exception|
    render file: "#{Rails.root}/public/403", formats: [:html], status: 403, layout: false
  end

  def index
  end

  private

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  inherit_resources

  belongs_to :book, :optional => true do
    belongs_to :chapter, :optional => true do
      belongs_to :section
    end
  end

  actions :all, :except => [:index, :show, :create]

  def create
    @section = Section.find(params[:section_id])

    @attachment = @section.attachments.create(:file => params[:file])

    respond_to do |format|
      format.json { render :json => @attachment }
    end
  end

  private

  def permitted_params
    params.permit(:attachment => :file)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  inherit_resources
  load_and_authorize_resource

  actions :all

  def sort
    @book = Book.find(params[:book_id])

    @book.sort_childrens(params[:chapter])

    render :nothing => true and return
  end

  protected

  def permitted_params
    params.permit(:book => :title)
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  inherit_resources
  load_and_authorize_resource

  actions :all, :except => :index

  belongs_to :book

  protected

  def permitted_params
    params.permit(:chapter => :title)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  inherit_resources
  load_and_authorize_resource

  actions :all, :except => [:index, :show]

  belongs_to :book, :optional => true do
    belongs_to :chapter, :optional => true
  end

  def create
    create! { book_chapter_path(@book, @chapter) }
  end

  def update
    update! {
      if request.xhr?
        render :nothing => true and return
      else
        redirect_to book_chapter_path(@book, @chapter) and return
      end
    }
  end

  protected

  def permitted_params
     { :section => params.fetch(:section, {}).permit(:title, :text) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def document_title
    [page_title, I18n.t('site_name')].compact.join(' / ')
  end

  def page_title(title = nil)
    @page_title ||= I18n.t("page_title.#{controller_name}.#{action_name}", :title => title).html_safe
  end
end

app/views/attachments/_attachment.html.erb
<div class="thumbnail">
  <h4><%= attachment.human_filename %></h4>

  <% if attachment.is_image? %>
    <%= image_tag attachment.file.thumb.url %>
  <% else %>
    <div class="content-type">
      <%= attachment.content_type %>
    </div>
  <% end %>

  <div class="actions">
    <%#= link_to 'Удалить', section_attachment_path(section, attachment), :method => :delete, :class => 'btn btn-danger btn-xs' %>
  </div>
</div>

app/views/books/_book.html.erb
<li class="list-group-item">
  <%= link_to book.title, book_path(book) %>

  <%= link_to 'Редактировать', edit_book_path(book), :class => 'btn btn-link' %>
</li>

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :title, :label => false, :autofocus => true,
              :input_html => { :class => 'title js-focused-input' },
              :wrapper_html => { :class => 'title-wrapper' },
              :placeholder => 'Название учебника' %>

  <div class="actions">
    <%= f.submit 'Сохранить', :class => 'btn btn-blue' %>
    <%= link_to 'Отмена', root_path, :class => 'btn btn-gray' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<ul class="list-group">
  <%= render collection %>
</ul>

<div>
  <%= link_to 'Добавить', new_book_path, :class => 'btn btn-blue' %>
</div>

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/show.html.erb
<h4><%= @book.title %></h4>

<h5>Оглавление:</h5>
<ul class="list-group js-sortable js-connected-sortable" data-sort-url="<%= book_sort_path(@book) %>">
  <%= render @book.chapters %>
</ul>

<div>
  <%= link_to 'Добавить главу', new_book_chapter_path(@book), :class => 'btn btn-blue' %>
</div>

app/views/chapters/_chapter.html.erb
<li class="list-group-item chapter" id="chapter_<%= chapter.id %>">
  <%= link_to chapter.title, book_chapter_path(@book, chapter) %>

  <%= link_to 'Редактировать', edit_book_chapter_path(@book, chapter), :class => 'btn btn-link' %>
</li>

app/views/chapters/_form.html.erb
<%= simple_form_for [@book, @chapter] do |f| %>
  <%= f.input :title, :label => false, :autofocus => true,
              :input_html => { :class => 'title js-focused-input' },
              :wrapper_html => { :class => 'title-wrapper' },
              :placeholder => 'Название главы' %>

  <div class="actions">
    <%= f.submit 'Сохранить', :class => 'btn btn-blue' %>
    <%= link_to 'Отмена', book_path(@book), :class => 'btn btn-gray' %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<%= render 'form' %>

app/views/chapters/new.html.erb
<%= render 'form' %>

app/views/chapters/show.html.erb
<h4><%= @chapter.title %></h4>

<%= render @chapter.sections %>

<div>
  <%= link_to 'Добавить параграф', new_book_chapter_section_path(@book, @chapter), :class => 'btn btn-blue' %>
</div>

app/views/commons/_header.html.erb
<%= link_to root_path, :class => 'navbar-brand' do %>
  <span class="logo"></span>
  ebook
<% end %>

<% if user_signed_in? %>
  <ul class="nav navbar-nav navbar-right navbar-profile">
    <li class="dropdown profile-dropdown">
      <%= link_to '#', :class => 'dropdown-toggle', :data => { :toggle => :dropdown } do %>
        <%= image_tag current_user.gravatar_url, :class => 'img-avatar img-circle' %>
      <% end %>
      <ul class="dropdown-menu">
        <li><%= link_to 'Редактировать профиль', edit_user_registration_path %></li>
        <li class="divider"></li>
        <li><%= link_to 'Выход', destroy_user_session_path, :method => :delete %></li>
      </ul>
    </li>
  </ul>
<% else %>
<% end %>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><%= document_title %></title>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body class="<%= controller_name %>">

    <header class="navbar navbar-static-top header" role="banner">
      <div class="container-fluid">
        <nav class="navbar-collapse" role="navigation">
          <%= render 'commons/header' %>
        </nav>
      </div>
    </header>

    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 main">
          <%= yield :navigation %>

          <%= yield :content %>
        </div>
      </div>
    </div>

    <%= render :partial => 'commons/flash' %>

    <%= render :partial => 'commons/metrika' if Rails.env.production? %>
  </body>
</html>

app/views/layouts/public.html.erb
<%= content_for :navigation do %>
  <div class="breadcrumb">
    <%= render_navigation :renderer => :breadcrumbs, :join_with => ' / ' %>
  </div>
<% end %>

<%= content_for :content do %>
  <%= yield %>
<% end %>

<%= render :file => 'layouts/base' %>

app/views/sections/_form.html.erb
<%= simple_form_for [@book, @chapter, @section], :html => { :class => 'section-form' } do |f| %>
  <%= f.input :title, :label => false, :autofocus => true,
              :input_html => { :class => 'title js-focused-input' },
              :wrapper_html => { :class => 'title-wrapper' },
              :placeholder => 'Название параграфа' %>

  <%= f.input :text, :label => false,
              :wrapper_html => { :class => 'text-wrapper' },
              :placeholder => 'Содержание параграфа' %>

  <div class="actions">
    <%= f.submit 'Сохранить', :class => 'btn btn-blue' %>
    <%= link_to 'Отмена', book_chapter_path(@book, @chapter), :class => 'btn btn-gray' %>
  </div>
<% end %>

app/views/sections/_section.html.erb
<div class="section" id="section_<%= section.id %>">
  <h4>
    <%= section.title? ? section.title : 'Параграф без названия' %>

    <span class="pull-right">
      <%= link_to 'Редактировать', edit_book_chapter_section_path(@book, @chapter, section), :class => 'btn btn-link' %>
      <%= link_to 'Удалить', book_chapter_section_path(@book, @chapter, section), :class => 'btn btn-link', :method => :delete %>
    </span>
  </h4>

  <div class="editor js-editor" data-section="<%= section.id %>" data-url="<%= book_chapter_section_path(@book, @chapter, section) %>">
    <%= section.text.html_safe %>
  </div>

  <%= simple_form_for [@book, @chapter, section], :html => { :class => 'section-form js-form', :remote => true } do |f| %>
    <%= f.input :text, :label => false, :as => :hidden, :input_html => { :class => 'js-editable' }%>
  <% end %>


  <div class="attachments">
    <%= render section.attachments %>

    <%= simple_form_for([@book, @chapter, section, section.attachments.new], :html => { :multipart => true, :class => 'dropzone js-dropzone' }) do |f| %>
      <%= f.input :file, :as => :hidden, :input_html => { :multiple => true, :name => 'section[file]' }, :wrapper_html => { :class => :failback } %>
    <% end %>
  </div>
</div>

app/views/sections/edit.html.erb
<%= render 'form' %>

app/views/sections/new.html.erb
<%= render 'form' %>